permalink: /:year:month:day/:title.html
url: #Your url here
baseurl: /project
buildtime: "1591286400"

# variables
name: Tang's blog
description: This is a personal blog to share life and knowledge
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true

## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  # disqus:
  #   shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : "fce91946ba9381818c17" # GitHub Application Client ID
    clientSecret: "3dcb10278c52274868a8bfc6faa955b8b684c062" # GitHub Application Client Secret
    repository  : "https://jaytanng.github.io/" # GitHub repo
    owner       : "JayTanng" # GitHub repo owner
    admin: ["JayTanng"] # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST. # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  # valine:
  #   app_id      : # LeanCloud App id
  #   app_key     : # LeanCloud App key
  #   placeholder : # Prompt information
  #   visitor     : # false (default)
  #   meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site